server:
  port: 8083

spring:
  application:
    name: risk-assessment-service

# Configuration Eureka supprimée

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized